services:
  - type: web
    name: headless-doc-api
    env: docker
    region: ohio
    plan: starter
    healthCheckPath: /health

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: OPENAI_API_KEY
        sync: false